version: '2.1'
services:
  start-watch:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - start-watch
    volumes:
      - .:/spotify-radio
      -  node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000
  e2e:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - test:docker:e2e
    volumes:
      - .:/spotify-radio
      -  node_modules:/spotify-radio/node_modules
  test:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:docker
    volumes:
      - .:/spotify-radio
      -  node_modules:/spotify-radio/node_modules
  test-coverage:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:docker:coverage
    volumes:
      - .:/spotify-radio
      -  node_modules:/spotify-radio/node_modules
volumes:
  node_modules: {}